#
# This GitHub action runs Packer go tests across
# Windows, Linux, and MacOS runners.
#

name: "Go Test"

on:
  - workflow_dispatch
  - pull_request

permissions:
  contents: read

jobs:
  get-go-version:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.get-go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@v3
      - name: 'Determine Go version'
        id: get-go-version
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "::set-output name=go-version::$(cat .go-version)"
  linux-go-tests:
    runs-on: ubuntu-latest
    needs: get-go-version
    name: Linux Go tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - run: go test -race -count 1 ./... -timeout=3m
  darwin-go-tests:
    runs-on: macos-latest
    needs: get-go-version
    name: Darwin Go tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - run: go test -race -count 1 ./... -timeout=3m
  windows-go-tests:
    runs-on: windows-latest
    needs: get-go-version
    name: Windows Go tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.get-go-version.outputs.go-version }}
      - run: go test -race -count 1 ./... -timeout=3m
